// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4k-sP9s8PCqiwLBzfEtusVpCpul4eZFY',
    appId: '1:709043431139:web:21e649b42c08bfa03187d6',
    messagingSenderId: '709043431139',
    projectId: 'atelier-manager-763ee',
    authDomain: 'atelier-manager-763ee.firebaseapp.com',
    storageBucket: 'atelier-manager-763ee.firebasestorage.app',
    measurementId: 'G-FLMXLTSV2C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyveiad26i3XLyCVboZc5WmlPX1z2fiBo',
    appId: '1:709043431139:android:fbe1c12fedbbc4a83187d6',
    messagingSenderId: '709043431139',
    projectId: 'atelier-manager-763ee',
    storageBucket: 'atelier-manager-763ee.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4k-sP9s8PCqiwLBzfEtusVpCpul4eZFY',
    appId: '1:709043431139:web:c8bb72fe324af47c3187d6',
    messagingSenderId: '709043431139',
    projectId: 'atelier-manager-763ee',
    authDomain: 'atelier-manager-763ee.firebaseapp.com',
    storageBucket: 'atelier-manager-763ee.firebasestorage.app',
    measurementId: 'G-S4BT1RBWG5',
  );
}
